const { v4: uuid } = require('uuid');
const crypto = require('crypto');

function hash(pw) {
  const salt = crypto.randomBytes(16).toString('hex');
  return `${salt}:${crypto.scryptSync(pw, salt, 64).toString('hex')}`;
}

// ── Date helpers (everything is relative to "now" so the demo always feels current) ──
const days = (n) => new Date(Date.now() + n * 864e5).toISOString().slice(0, 10);
const dt = (n, h = 9, m = 0) => { const d = new Date(Date.now() + n * 864e5); d.setHours(h, m, 0, 0); return d.toISOString(); };
// A date `aheadDays` from now, stamped with a birth year — drives the birthday banner.
const birthday = (aheadDays, year) => { const d = new Date(Date.now() + aheadDays * 864e5); return `${year}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`; };
// First-of-month minus `offset` months, on a given day — for multi-month financial history.
const monthDay = (offset, day) => { const d = new Date(); d.setMonth(d.getMonth() - offset, day); return d.toISOString().slice(0, 10); };
// The Sunday that starts this week.
const weekStart = () => { const d = new Date(); d.setDate(d.getDate() - d.getDay()); return d; };
const weekDay = (i) => { const d = weekStart(); d.setDate(d.getDate() + i); return d.toISOString().slice(0, 10); };

/**
 * Populate a brand-new household with a rich, realistic dataset across every
 * module. Used both for the dev demo account and the live "Explore the demo
 * home" sandbox (a fresh isolated copy per visitor).
 *
 * @returns {{ householdId:string, ownerId:string, ownerEmail:string }}
 */
function seedHousehold(db, opts = {}) {
  const {
    name = 'The Hart Family',
    ownerName = 'Jordan Hart',
    ownerEmail,                 // required-ish; generated by caller for sandboxes
    ownerPassword,              // optional — omit for password-less sandbox owners
    address = '14 Maple Grove Lane',
  } = opts;

  const hid = uuid();
  db.prepare('INSERT INTO households (id, name, address, invite_code) VALUES (?,?,?,?)')
    .run(hid, name, address, Math.random().toString(36).slice(2, 8).toUpperCase());

  // ── Members ──
  const members = [
    { key: 'Jordan', name: ownerName,    email: ownerEmail, role: 'owner',  color: '#6366f1', pts: 60,  bday: '1986-09-21', pw: ownerPassword },
    { key: 'Riley',  name: 'Riley Hart', email: null,       role: 'parent', color: '#ec4899', pts: 35,  bday: '1988-03-12' },
    { key: 'Ava',    name: 'Ava Hart',   email: null,       role: 'child',  color: '#14b8a6', pts: 165, bday: '2014-06-18' },
    { key: 'Leo',    name: 'Leo Hart',   email: null,       role: 'child',  color: '#f59e0b', pts: 95,  bday: birthday(6, 2016) },
  ];
  const ids = {};
  for (const m of members) {
    const id = uuid(); ids[m.key] = id;
    db.prepare(`INSERT INTO users (id, household_id, email, password_hash, display_name, role, avatar_color, points, birthday)
                VALUES (?,?,?,?,?,?,?,?,?)`)
      .run(id, hid, m.email || null, m.pw ? hash(m.pw) : null, m.name, m.role, m.color, m.pts, m.bday);
  }
  const { Jordan, Riley, Ava, Leo } = ids;

  const ins = (table, cols, rows) => {
    const stmt = db.prepare(`INSERT INTO ${table} (id, household_id, ${cols.join(',')}) VALUES (?, ?, ${cols.map(() => '?').join(',')})`);
    for (const r of rows) stmt.run(uuid(), hid, ...cols.map(c => r[c] ?? null));
  };

  // ── Calendar (this week + next, color-coded per member) ──
  ins('events', ['title', 'start_at', 'end_at', 'member_id', 'color', 'category', 'all_day', 'location'], [
    { title: 'Soccer practice', start_at: dt(0, 16), end_at: dt(0, 17, 30), member_id: Ava, color: '#14b8a6', category: 'sports', location: 'Riverside Field' },
    { title: 'Family movie night', start_at: dt(0, 19), member_id: null, color: '#6366f1', category: 'family', location: 'Living room' },
    { title: 'Dentist — Leo', start_at: dt(1, 10), member_id: Leo, color: '#f59e0b', category: 'medical', location: 'Bright Smiles Dental' },
    { title: 'Book club', start_at: dt(1, 19, 30), member_id: Riley, color: '#ec4899', category: 'general' },
    { title: 'Riley — work trip', start_at: dt(2, 8), end_at: dt(3, 18), member_id: Riley, color: '#ec4899', category: 'work', all_day: 1 },
    { title: 'Grocery run', start_at: dt(2, 11), member_id: Jordan, color: '#10b981', category: 'errand' },
    { title: 'Parent-teacher conference', start_at: dt(3, 15), member_id: Leo, color: '#f59e0b', category: 'school', location: 'Maple Grove Elementary' },
    { title: 'Ava piano recital', start_at: dt(4, 18), member_id: Ava, color: '#14b8a6', category: 'school', location: 'Community Hall' },
    { title: 'Date night', start_at: dt(5, 19), member_id: null, color: '#8b5cf6', category: 'family' },
    { title: 'Car service appointment', start_at: dt(6, 9), member_id: Jordan, color: '#6366f1', category: 'errand', location: 'Toyota Service Center' },
    { title: "Leo's birthday party 🎉", start_at: dt(6, 14), member_id: Leo, color: '#f59e0b', category: 'birthday', all_day: 1 },
    { title: 'Farmers market', start_at: dt(7, 9, 30), member_id: null, color: '#10b981', category: 'errand' },
    { title: 'Swim lessons', start_at: dt(8, 17), member_id: Ava, color: '#14b8a6', category: 'sports' },
  ]);
  // A few repeating events to show recurrence on the calendar.
  ins('events', ['title', 'start_at', 'member_id', 'color', 'category', 'recurrence'], [
    { title: 'Trash night', start_at: dt(0, 20), member_id: null, color: '#64748b', category: 'general', recurrence: 'weekly' },
    { title: 'Soccer practice', start_at: dt(2, 16), member_id: Ava, color: '#14b8a6', category: 'sports', recurrence: 'weekly' },
    { title: 'Pay day', start_at: dt(1, 0), member_id: Jordan, color: '#10b981', category: 'general', recurrence: 'monthly' },
  ]);

  // ── Chores ──
  ins('chores', ['title', 'assignee_id', 'points', 'recurrence', 'due_date', 'icon', 'description'], [
    { title: 'Take out trash & recycling', assignee_id: Leo, points: 5, recurrence: 'weekly', due_date: days(0), icon: 'Trash2', description: 'Bins go to the curb the night before pickup.' },
    { title: 'Load the dishwasher', assignee_id: Ava, points: 5, recurrence: 'daily', due_date: days(0), icon: 'Utensils' },
    { title: 'Make your bed', assignee_id: Leo, points: 3, recurrence: 'daily', due_date: days(0), icon: 'BedDouble' },
    { title: 'Walk the dog', assignee_id: Ava, points: 8, recurrence: 'daily', due_date: days(0), icon: 'Dog' },
    { title: 'Feed the dog', assignee_id: Leo, points: 3, recurrence: 'daily', due_date: days(0), icon: 'PawPrint' },
    { title: 'Vacuum living room', assignee_id: Riley, points: 10, recurrence: 'weekly', due_date: days(1), icon: 'Wind' },
    { title: 'Mow the lawn', assignee_id: Jordan, points: 15, recurrence: 'weekly', due_date: days(2), icon: 'Trees' },
    { title: 'Fold & put away laundry', assignee_id: Ava, points: 7, recurrence: 'weekly', due_date: days(1), icon: 'Shirt' },
    { title: 'Wipe down bathrooms', assignee_id: Riley, points: 10, recurrence: 'weekly', due_date: days(3), icon: 'Sparkles' },
    { title: 'Water the plants', assignee_id: Leo, points: 4, recurrence: 'weekly', due_date: days(2), icon: 'Leaf' },
  ]);

  // ── Goals ──
  ins('goals', ['title', 'description', 'category', 'target', 'current', 'unit', 'member_id', 'due_date'], [
    { title: 'Summer vacation fund', description: 'Saving for a week at the lake', category: 'finance', target: 4000, current: 2350, unit: '$', due_date: days(110) },
    { title: 'Read 20 books this year', description: '', category: 'learning', target: 20, current: 13, unit: 'books', member_id: Ava },
    { title: 'Walk 10k steps a day (avg)', description: '', category: 'health', target: 10000, current: 8200, unit: 'steps', member_id: Jordan },
    { title: 'Declutter the garage', description: 'One zone per weekend', category: 'home', target: 100, current: 55, unit: '%' },
    { title: 'Family game nights', description: 'A goal of 12 this season', category: 'family', target: 12, current: 7, unit: 'nights' },
    { title: 'Pay off the credit card', description: '', category: 'finance', target: 1800, current: 560, unit: '$', due_date: days(75) },
  ]);

  // ── Rewards ──
  ins('rewards', ['title', 'description', 'cost', 'icon'], [
    { title: 'Movie night pick', description: 'Choose the family movie', cost: 30, icon: 'Clapperboard' },
    { title: '30 min extra screen time', description: '', cost: 40, icon: 'Tv' },
    { title: 'Ice cream trip', description: 'A scoop of your choice', cost: 60, icon: 'IceCream' },
    { title: 'Stay up 30 min late', description: 'Weekend only', cost: 50, icon: 'Moon' },
    { title: '$10 allowance bonus', description: '', cost: 100, icon: 'DollarSign' },
    { title: 'Friend sleepover', description: 'Invite a friend over', cost: 150, icon: 'Users' },
    { title: 'Day trip of your choice', description: 'Zoo, museum, or beach', cost: 250, icon: 'Bus' },
  ]);

  // ── Lists ──
  const gid = uuid();
  db.prepare(`INSERT INTO lists (id, household_id, name, type, icon, color) VALUES (?,?,?,?,?,?)`).run(gid, hid, 'Groceries', 'grocery', 'ShoppingCart', '#10b981');
  const li = db.prepare(`INSERT INTO list_items (id, household_id, list_id, name, qty, category, done) VALUES (?,?,?,?,?,?,?)`);
  ([
    ['Milk', '2 gal', 'Dairy', 0], ['Greek yogurt', '4', 'Dairy', 0], ['Eggs', '1 dozen', 'Dairy', 0],
    ['Bananas', '', 'Produce', 0], ['Spinach', '1 bag', 'Produce', 0], ['Bell peppers', '3', 'Produce', 1],
    ['Apples', '6', 'Produce', 0], ['Chicken breast', '2 lb', 'Meat', 0], ['Ground beef', '1 lb', 'Meat', 0],
    ['Pasta', '2 boxes', 'Pantry', 0], ['Olive oil', '', 'Pantry', 1], ['Cereal', '', 'Pantry', 0],
    ['Coffee', '', 'Pantry', 0], ['Paper towels', '', 'Household', 0], ['Dish soap', '', 'Household', 0],
    ['Toothpaste', '', 'Household', 1],
  ]).forEach(([n, q, c, d]) => li.run(uuid(), hid, gid, n, q, c, d));

  const tid = uuid();
  db.prepare(`INSERT INTO lists (id, household_id, name, type, icon, color) VALUES (?,?,?,?,?,?)`).run(tid, hid, 'Weekend to-do', 'todo', 'ListChecks', '#6366f1');
  ([['Wash the car', 0], ['Return library books', 0], ['Fix the fence gate', 0], ['Rake leaves', 1], ['Plan Leo\'s party', 0]])
    .forEach(([n, d]) => li.run(uuid(), hid, tid, n, '', '', d));

  const pid = uuid();
  db.prepare(`INSERT INTO lists (id, household_id, name, type, icon, color) VALUES (?,?,?,?,?,?)`).run(pid, hid, 'Lake trip packing', 'packing', 'Plane', '#f59e0b');
  (['Sunscreen', 'Swimsuits', 'Beach towels', 'Cooler', 'First-aid kit', 'Board games']).forEach(n => li.run(uuid(), hid, pid, n, '', '', 0));

  // ── Recipes + a full week of meals ──
  const recipes = [
    { name: 'Sheet-pan chicken fajitas', desc: 'Weeknight favorite', ing: [['Chicken breast', '1.5 lb'], ['Bell peppers', '3'], ['Onion', '1'], ['Tortillas', '8'], ['Fajita seasoning', '1 pkt']], inst: 'Slice everything, toss with oil + seasoning, roast at 425°F for 20 min.', prep: 30, serv: 4, tags: 'dinner,easy' },
    { name: 'Spaghetti & meatballs', desc: 'Crowd pleaser', ing: [['Spaghetti', '1 lb'], ['Ground beef', '1 lb'], ['Marinara', '1 jar'], ['Parmesan', '']], inst: 'Simmer meatballs in sauce; boil pasta; combine.', prep: 40, serv: 5, tags: 'dinner' },
    { name: 'Taco Tuesday', desc: '', ing: [['Ground beef', '1 lb'], ['Taco shells', '12'], ['Lettuce', '1'], ['Cheese', ''], ['Salsa', '']], inst: 'Brown beef with taco seasoning; assemble.', prep: 25, serv: 4, tags: 'dinner,kids' },
    { name: 'Pancakes', desc: 'Weekend treat', ing: [['Flour', '2 cups'], ['Eggs', '2'], ['Milk', '1.5 cups'], ['Maple syrup', '']], inst: 'Mix, griddle, flip.', prep: 20, serv: 4, tags: 'breakfast' },
  ];
  const rids = {};
  const rstmt = db.prepare(`INSERT INTO recipes (id, household_id, name, description, ingredients, instructions, prep_minutes, servings, tags) VALUES (?,?,?,?,?,?,?,?,?)`);
  for (const r of recipes) { const id = uuid(); rids[r.name] = id; rstmt.run(id, hid, r.name, r.desc, JSON.stringify(r.ing.map(([name, qty]) => ({ name, qty }))), r.inst, r.prep, r.serv, r.tags); }
  ins('meals', ['date', 'meal_type', 'title', 'recipe_id'], [
    { date: weekDay(0), meal_type: 'breakfast', title: 'Pancakes', recipe_id: rids['Pancakes'] },
    { date: weekDay(0), meal_type: 'dinner', title: 'Sheet-pan chicken fajitas', recipe_id: rids['Sheet-pan chicken fajitas'] },
    { date: weekDay(1), meal_type: 'dinner', title: 'Spaghetti & meatballs', recipe_id: rids['Spaghetti & meatballs'] },
    { date: weekDay(2), meal_type: 'dinner', title: 'Taco Tuesday', recipe_id: rids['Taco Tuesday'] },
    { date: weekDay(3), meal_type: 'dinner', title: 'Grilled salmon & veggies' },
    { date: weekDay(4), meal_type: 'dinner', title: 'Homemade pizza' },
    { date: weekDay(5), meal_type: 'dinner', title: 'Leftovers / fend for yourself' },
    { date: weekDay(6), meal_type: 'breakfast', title: 'Eggs & toast' },
    { date: weekDay(6), meal_type: 'dinner', title: 'Sunday roast chicken' },
  ]);

  // ── Bills ──
  ins('bills', ['name', 'amount', 'category', 'frequency', 'next_due', 'autopay', 'status'], [
    { name: 'Mortgage', amount: 1850, category: 'housing', frequency: 'monthly', next_due: days(5), autopay: 1, status: 'upcoming' },
    { name: 'Electric — PowerCo', amount: 142.5, category: 'utilities', frequency: 'monthly', next_due: days(8), status: 'upcoming' },
    { name: 'Internet — FiberNet', amount: 79.99, category: 'utilities', frequency: 'monthly', next_due: days(-2), status: 'overdue' },
    { name: 'Car insurance', amount: 168, category: 'insurance', frequency: 'monthly', next_due: days(12), autopay: 1, status: 'upcoming' },
    { name: 'Netflix', amount: 22.99, category: 'subscriptions', frequency: 'monthly', next_due: days(15), autopay: 1, status: 'upcoming' },
    { name: 'Water & sewer', amount: 64, category: 'utilities', frequency: 'monthly', next_due: days(20), status: 'upcoming' },
    { name: 'Phone plan', amount: 95, category: 'utilities', frequency: 'monthly', next_due: days(18), autopay: 1, status: 'upcoming' },
    { name: 'Gym membership', amount: 45, category: 'subscriptions', frequency: 'monthly', next_due: days(25), autopay: 1, status: 'upcoming' },
  ]);

  // ── Finance: accounts, budgets, and six months of transactions ──
  ins('accounts', ['name', 'type', 'balance', 'institution'], [
    { name: 'Everyday checking', type: 'checking', balance: 6240.18, institution: 'First National' },
    { name: 'Emergency savings', type: 'savings', balance: 18500, institution: 'First National' },
    { name: 'Vacation fund', type: 'savings', balance: 2350, institution: 'Ally' },
    { name: 'Visa rewards', type: 'credit', balance: 1240.55, institution: 'Chase' },
    { name: 'Car loan', type: 'loan', balance: 11200, institution: 'Toyota Financial' },
    { name: "Kids' 529 plan", type: 'investment', balance: 14800, institution: 'Vanguard' },
  ]);
  ins('budgets', ['category', 'monthly_limit', 'icon'], [
    { category: 'groceries', monthly_limit: 800, icon: 'ShoppingCart' },
    { category: 'dining out', monthly_limit: 300, icon: 'Utensils' },
    { category: 'auto & maintenance', monthly_limit: 250, icon: 'Car' },
    { category: 'entertainment', monthly_limit: 150, icon: 'Clapperboard' },
    { category: 'utilities', monthly_limit: 450, icon: 'Zap' },
    { category: 'kids & school', monthly_limit: 200, icon: 'GraduationCap' },
  ]);
  const tx = db.prepare(`INSERT INTO transactions (id, household_id, type, amount, category, description, member_id, date) VALUES (?,?,?,?,?,?,?,?)`);
  // Six months of history → a full cashflow trend chart.
  for (let mo = 5; mo >= 0; mo--) {
    tx.run(uuid(), hid, 'income', 5200, 'salary', 'Paycheck', Jordan, monthDay(mo, 1));
    tx.run(uuid(), hid, 'income', 2100, 'salary', 'Paycheck', Riley, monthDay(mo, 15));
    tx.run(uuid(), hid, 'expense', 720 + Math.round(Math.random() * 160), 'groceries', 'Grocery shopping', Jordan, monthDay(mo, 6));
    tx.run(uuid(), hid, 'expense', 180 + Math.round(Math.random() * 120), 'dining out', 'Restaurants', Riley, monthDay(mo, 12));
    tx.run(uuid(), hid, 'expense', 130 + Math.round(Math.random() * 60), 'utilities', 'Utilities', Jordan, monthDay(mo, 9));
    tx.run(uuid(), hid, 'expense', 90 + Math.round(Math.random() * 90), 'entertainment', 'Family fun', null, monthDay(mo, 18));
    tx.run(uuid(), hid, 'expense', 60 + Math.round(Math.random() * 140), 'kids & school', 'School & activities', Riley, monthDay(mo, 20));
  }
  // A few recent, current-month extras.
  tx.run(uuid(), hid, 'income', 150, 'other', 'Yard sale', Jordan, days(-2));
  tx.run(uuid(), hid, 'expense', 49.99, 'auto & maintenance', 'Oil change', Jordan, days(-1));

  // ── Utilities + reading history ──
  const utils = [
    { name: 'Electricity', provider: 'PowerCo', type: 'electric', acct: '****4821', est: 142, unit: 'kWh', base: 900 },
    { name: 'Water & Sewer', provider: 'City Utilities', type: 'water', acct: '****9032', est: 64, unit: 'gal', base: 4200 },
    { name: 'Natural Gas', provider: 'Metro Gas', type: 'gas', acct: '****1188', est: 58, unit: 'therm', base: 45 },
    { name: 'Internet', provider: 'FiberNet', type: 'internet', acct: '****7741', est: 80, unit: '', base: 0 },
  ];
  const ustmt = db.prepare(`INSERT INTO utilities (id, household_id, name, provider, type, account_number, monthly_estimate, unit) VALUES (?,?,?,?,?,?,?,?)`);
  const rdstmt = db.prepare(`INSERT INTO utility_readings (id, household_id, utility_id, reading, cost, period, recorded_at) VALUES (?,?,?,?,?,?,?)`);
  for (const u of utils) {
    const uid = uuid();
    ustmt.run(uid, hid, u.name, u.provider, u.type, u.acct, u.est, u.unit);
    for (let mo = 3; mo >= 0; mo--) {
      const reading = u.base ? Math.round(u.base * (1 + (3 - mo) * 0.05)) : 0;
      const cost = Math.round(u.est * (0.85 + Math.random() * 0.3) * 100) / 100;
      const period = monthDay(mo, 1).slice(0, 7);
      rdstmt.run(uuid(), hid, uid, reading, cost, period, monthDay(mo, 2) + 'T10:00:00.000Z');
    }
  }

  // ── Assets + maintenance (upcoming, overdue, and completed history) ──
  const carId = uuid();
  db.prepare(`INSERT INTO assets (id, household_id, name, type, make, model, year, identifier, purchase_date, purchase_price, current_value, mileage, icon, location)
              VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)`)
    .run(carId, hid, 'Family SUV', 'vehicle', 'Toyota', 'Highlander', 2021, '1HGBH41JXMN····', days(-900), 38000, 29500, 41200, 'Car', 'Garage');
  const car2 = uuid();
  db.prepare(`INSERT INTO assets (id, household_id, name, type, make, model, year, purchase_price, current_value, mileage, icon, location)
              VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`)
    .run(car2, hid, 'Commuter sedan', 'vehicle', 'Honda', 'Civic', 2018, 22000, 14000, 78400, 'Car', 'Driveway');
  ins('assets', ['name', 'type', 'make', 'model', 'purchase_price', 'current_value', 'icon', 'warranty_expires', 'location'], [
    { name: 'Refrigerator', type: 'appliance', make: 'LG', model: 'InstaView', purchase_price: 2400, current_value: 1500, icon: 'Refrigerator', warranty_expires: days(220), location: 'Kitchen' },
    { name: 'HVAC system', type: 'home', make: 'Carrier', model: 'Infinity', purchase_price: 6800, current_value: 5200, icon: 'Wind', location: 'Basement' },
    { name: 'Washer & dryer', type: 'appliance', make: 'Samsung', model: 'FlexWash', purchase_price: 1800, current_value: 1100, icon: 'Shirt', warranty_expires: days(-30), location: 'Laundry room' },
    { name: 'Lawn mower', type: 'tool', make: 'Honda', model: 'HRX217', purchase_price: 650, current_value: 400, icon: 'Trees', location: 'Shed' },
  ]);
  const mt = db.prepare(`INSERT INTO maintenance (id, household_id, asset_id, title, type, due_date, due_mileage, completed_at, cost, provider, recurrence_months, recurrence_miles, status, notes)
                         VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)`);
  // Upcoming / overdue
  mt.run(uuid(), hid, carId, 'Oil change', 'service', days(7), 44000, null, 0, 'Toyota Service', 6, 5000, 'upcoming', 'Synthetic 0W-20');
  mt.run(uuid(), hid, carId, 'Tire rotation', 'service', days(16), 44000, null, 0, 'Toyota Service', 6, 5000, 'upcoming', '');
  mt.run(uuid(), hid, carId, 'Registration renewal', 'registration', days(-3), null, null, 0, 'DMV', 12, 0, 'overdue', 'Renew online');
  mt.run(uuid(), hid, car2, 'Brake inspection', 'inspection', days(28), 80000, null, 0, '', 12, 12000, 'upcoming', '');
  mt.run(uuid(), hid, car2, 'State safety inspection', 'inspection', days(-6), null, null, 0, '', 12, 0, 'overdue', '');
  // Completed history (shows service log + costs)
  mt.run(uuid(), hid, carId, 'Oil change', 'service', days(-175), 39000, days(-175), 62.5, 'Toyota Service', 6, 5000, 'done', '');
  mt.run(uuid(), hid, carId, 'New wiper blades', 'repair', days(-90), null, days(-90), 28, 'AutoZone', 0, 0, 'done', '');
  mt.run(uuid(), hid, car2, 'Battery replacement', 'repair', days(-120), null, days(-120), 145, 'Firestone', 0, 0, 'done', '');

  // ── Contacts ──
  ins('contacts', ['name', 'relationship', 'category', 'phone', 'email'], [
    { name: 'Poison Control', relationship: '', category: 'emergency', phone: '1-800-222-1222' },
    { name: 'Dr. Patel (Pediatrician)', relationship: 'Doctor', category: 'medical', phone: '555-0142', email: 'frontdesk@brightpeds.example' },
    { name: 'Maple Grove Elementary', relationship: 'School', category: 'school', phone: '555-0188' },
    { name: 'Mike — Plumber', relationship: 'Service', category: 'service', phone: '555-0173' },
    { name: 'Sunshine HVAC', relationship: 'Service', category: 'service', phone: '555-0166' },
    { name: 'Grandma Hart', relationship: 'Grandmother', category: 'family', phone: '555-0119' },
    { name: 'Aunt Dana', relationship: 'Emergency pickup', category: 'family', phone: '555-0150' },
  ]);

  // ── Notes ──
  ins('notes', ['title', 'body', 'color', 'pinned', 'author_id'], [
    { title: 'WiFi password', body: 'Network: HartHome\nPassword: maple-grove-2024', color: '#dbeafe', pinned: 1, author_id: Jordan },
    { title: 'Babysitter notes', body: 'Bedtime 8pm. Leo needs his night light. Snacks in the pantry. Emergency #s on the fridge.', color: '#fef3c7', author_id: Riley },
    { title: 'Dog feeding', body: 'Buddy eats 1 cup, twice a day. No table scraps!', color: '#dcfce7', author_id: Ava },
    { title: 'Costco reminders', body: 'Check the freezer before buying meat. Bring the bags!', color: '#ede9fe', author_id: Jordan },
  ]);

  // ── Documents ──
  ins('documents', ['name', 'category', 'reference', 'expires_at', 'notes'], [
    { name: 'Passport — Jordan', category: 'identity', reference: 'C12345678', expires_at: days(40), notes: 'Renew soon!' },
    { name: 'Auto insurance policy', category: 'insurance', reference: 'POL-44821', expires_at: days(120) },
    { name: "Leo's birth certificate", category: 'identity', reference: '', notes: 'In the fireproof box' },
    { name: 'Home warranty', category: 'warranty', reference: 'HW-9921', expires_at: days(200) },
    { name: 'Vehicle title — Highlander', category: 'vehicle', reference: '' },
  ]);

  // ── Photos (family slideshow) — stable placeholder images ──
  ins('photos', ['url', 'caption', 'sort'], [
    { url: 'https://picsum.photos/seed/harthome-beach/1200/800', caption: 'Lake trip last summer', sort: 1 },
    { url: 'https://picsum.photos/seed/harthome-hike/1200/800', caption: 'Sunday hike', sort: 2 },
    { url: 'https://picsum.photos/seed/harthome-park/1200/800', caption: 'Ava at the park', sort: 3 },
    { url: 'https://picsum.photos/seed/harthome-bday/1200/800', caption: "Leo's last birthday", sort: 4 },
    { url: 'https://picsum.photos/seed/harthome-garden/1200/800', caption: 'Backyard evening', sort: 5 },
    { url: 'https://picsum.photos/seed/harthome-snow/1200/800', caption: 'First snow', sort: 6 },
  ]);

  // ── Devices ──
  ins('devices', ['name', 'type', 'pairing_code', 'widgets'], [
    { name: 'Kitchen wall display', type: 'wall', pairing_code: 'KTCHN1', widgets: '["clock","weather","calendar","chores","meals"]' },
    { name: 'Entryway tablet', type: 'tablet', pairing_code: 'ENTRY2', widgets: '["calendar","chores","lists"]' },
    { name: 'Living room TV', type: 'tv', pairing_code: 'LIVTV3', widgets: '["clock","calendar","bulletin"]' },
  ]);

  // ── Announcements ──
  const an = db.prepare('INSERT INTO announcements (id, household_id, author_id, body, created_at) VALUES (?,?,?,?,?)');
  an.run(uuid(), hid, Riley, 'Reminder: trash goes out tonight! 🗑️', dt(0, 8));
  an.run(uuid(), hid, Jordan, "Great job on chores this week, kids — pizza Friday! 🍕", dt(-1, 18));
  an.run(uuid(), hid, Ava, "Don't forget my recital is this week! 🎹", dt(-1, 20));

  // ── Activity feed ──
  const act = db.prepare('INSERT INTO activity (id, household_id, member_id, member_name, type, message, created_at) VALUES (?,?,?,?,?,?,?)');
  act.run(uuid(), hid, Ava, 'Ava Hart', 'chore', 'completed "Walk the dog" (+8 pts)', dt(0, 8, 30));
  act.run(uuid(), hid, Leo, 'Leo Hart', 'reward', 'redeemed "Movie night pick" for 30 pts', dt(0, 7, 45));
  act.run(uuid(), hid, Jordan, 'Jordan Hart', 'bill', 'paid Water & sewer ($64.00)', dt(-1, 12));
  act.run(uuid(), hid, Riley, 'Riley Hart', 'goal', 'updated "Declutter the garage" to 55%', dt(-1, 16));
  act.run(uuid(), hid, Ava, 'Ava Hart', 'chore', 'completed "Fold & put away laundry" (+7 pts)', dt(-2, 17));

  return { householdId: hid, ownerId: Jordan, ownerEmail: ownerEmail || null };
}

// Dev convenience: seed a fixed demo account once (idempotent).
function seedDemoOnce(db) {
  const exists = db.prepare('SELECT id FROM users WHERE email = ?').get('owner@harthome.demo');
  if (exists) return;
  console.log('  ↳ seeding demo household "The Hart Family"…');
  seedHousehold(db, { ownerEmail: 'owner@harthome.demo', ownerPassword: 'Demo123!' });
  console.log('  ↳ demo ready — sign in with owner@harthome.demo / Demo123!');
}

module.exports = seedDemoOnce;
module.exports.seedHousehold = seedHousehold;
